apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-claim
  labels:
    app: influxdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
