apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - port: 21
    targetPort: 21
    name: ftp
    protocol: TCP
  - port: 7000
    targetPort: 7000
    name: passiv0
    protocol: TCP
  - port: 7001
    targetPort: 7001
    name: passiv1
    protocol: TCP
  - port: 7002
    targetPort: 7002
    name: passiv2
    protocol: TCP
  - port: 7003
    targetPort: 7003
    name: passiv3
    protocol: TCP
  - port: 7004
    targetPort: 7004
    name: passiv4
    protocol: TCP
  - port: 7005
    targetPort: 7005
    name: passiv5
    protocol: TCP
