apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
  labels:
    app: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: wordpress
        image: ft_services/pma
        imagePullPolicy: Never
        livenessProbe:
            exec:
              command:
              - /liveness.sh
            initialDelaySeconds: 30
            periodSeconds: 10
        ports:
        - containerPort: 5000
