apiVersion: v1
kind: Service
metadata:
  name: pma
  labels:
    app: pma
spec:
  selector:
    app: pma
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    name: pma
    protocol: TCP
